--- #YAML:1.0
name:                     Net-SMS-MyTMN
version:                  0.08
abstract:                 Send SMS trough TMN
author:
  - Miguel Santinho <cpan@simplicidade.com>

license:                  perl
distribution_type:        module
installdirs:              site

requires:
  WWW::Mechanize:         1.22
  Crypt::SSLeay:          0.53

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-SMS-MyTMN

generated_by: Hand 1.0
